import type { Metadata } from 'next'
import FooterComponents from "@/components/FooterComponents";
import HeroComponents from "@/components/HeroComponents";
import NavigationComponents from "@/components/NavigationComponents";
import ServiceComponents from "@/components/ServiceComponents";


export const metadata: Metadata = {
  title: 'DanJala',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <>
      <NavigationComponents />
      <HeroComponents />
      <ServiceComponents />
      <FooterComponents />
    </>
  )
}
